name: 'Determine API Server versions'
description: 'Determine API Server versions'
inputs:
  long-vesion:
    description: 'Long version number'
    required: true
    default: ''
  beta-branch:
    description: 'Name of branch for beta builds'
    required: true
    default: ''
  dev-branch:
    description: 'Name of branch for experimental builds'
    required: false
    default: ''
outputs:
  branch:
    description: 'API Server branch'
    value: ${{ steps.versions.outputs.branch }}
  version:
    description: 'API Server version'
    value: ${{ steps.versions.outputs.version }}
runs:
  using: 'composite'
  steps:
    - id: versions
      name: Determine versions
      shell: bash
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]
         then
           VERSION="${{ github.ref_name }}"
           echo "stable release ${VERSION}"
           echo ::set-output name=branch::"stable"
           echo ::set-output name=version::"${VERSION}"
         elif [[ "${{ github.ref }}" == refs/heads/* && "${{ github.ref_name }}" == "${{ inputs.beta-branch }}" ]]
         then
           VERSION="${{ inputs.long-version }}"
           echo "beta build ${VERSION}"
           echo ::set-output name=branch::"beta"
           echo ::set-output name=version::"${VERSION}"
         elif [[ "${{ github.ref }}" == refs/heads/* && "${{ github.ref_name }}" == "${{ inputs.dev-branch }}" ]]
         then
           VERSION="${{ inputs.long-version }}"
           echo "dev build ${VERSION}"
           echo ::set-output name=branch::"experimental"
           echo ::set-output name=version::"${VERSION}"
         else
           echo "not uploading"
         fi
