name: 'Upload to S3'
description: 'Upload to S3'
inputs:
  source-filename:
    description: 'File to upload'
    required: true
    default: ''
  destination-filename:
    description: 'Target filename in s3'
    required: true
    default: ''
  host:
    description: 'Server endpoint'
    required: true
    default: 's3.bitfocus.io'
  bucket:
    description: 'Bucket to upload to'
    required: true
    default: ''
  access-key:
    description: 'Access Key'
    required: true
    default: ''
  secret-key:
    description: 'Secret Key'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Download minio client
      if: runner.os == 'Linux'
      shell: bash
      run: |
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
    - name: Download minio client
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://dl.minio.io/client/mc/release/windows-amd64/mc.exe" -OutFile "./mc"
        chmod +x mc
    - name: Download minio client
      if: runner.os == 'macOS'
      shell: bash
      run: |
        wget https://dl.min.io/client/mc/release/darwin-amd64/mc
        chmod +x mc

    - name: Upload file
      shell: bash
      run: |
        ./mc alias set remote/ https://${{ inputs.host }} ${{ inputs.access-key }} ${{ inputs.secret-key }}

        ./mc cp "${{ inputs.source-filename }}" "remote/${{ inputs.bucket }}/${{ inputs.destination-filename }}"
