name: SatellitePi Build

on:
  # TODO not on every push
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: build image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: install packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y packer

      - name: build image
        run: |
          cd pi-image
          sudo packer init satellitepi.pkr.hcl
          sudo packer build --var branch=${GITHUB_REF_NAME} satellitepi.pkr.hcl

      - name: compress image
        shell: bash
        run: |
          cd pi-image/output-satellitepi

          sudo apt-get install -y zerofree
          device="$(sudo losetup --partscan --show --find image)"
          sudo zerofree "${device}p2"
          sudo losetup --detach "$device"

          sudo gzip image

      - name: Determine files to upload
        id: filenames
        shell: bash
        run: |
          HASH=$(git rev-parse --short HEAD)
          COUNT=$(git rev-list --count HEAD)
          VERSION=$(node -e "console.log(require('./package.json').version)")

          echo ::set-output name=sourcename::"pi-image/output-satellitepi/image.gz"
          echo ::set-output name=targetname::"companion-satellite-pi-${COUNT}-${HASH}.img.gz"
          echo ::set-output name=longversion::"${VERSION}+${COUNT}-${HASH}"

      - name: Upload build
        uses: bitfocus/actions/upload-and-notify@main
        with:
          long-version: ${{ steps.filenames.outputs.longversion }}
          beta-branch: master

          source-filename: ${{ steps.filenames.outputs.sourcename }}
          destination-filename: ${{ steps.filenames.outputs.targetname }}
          s3-host: ${{ secrets.S3_HOST }}
          s3-bucket: ${{ secrets.S3_BUCKET }}/companion-satellite
          s3-access-key: ${{ secrets.S3_KEY }}
          s3-secret-key: ${{ secrets.S3_SECRET }}

          api-product: companion-satellite
          api-target: 'linux-img'
          api-secret: ${{ secrets.BITFOCUS_API_PROJECT_SECRET }}
